[package]
name = "csv"
version = "0.1.0"
authors = ["rob-ng <rob.nate.grove@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jestr = { path = "../jestr" }
